//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjF1Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FIA2022Entities : DbContext
    {
        public FIA2022Entities()
            : base("name=FIA2022Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carro> Carroes { get; set; }
        public virtual DbSet<Equipe> Equipes { get; set; }
        public virtual DbSet<Piloto> Pilotoes { get; set; }
        public virtual DbSet<PilotoCarro> PilotoCarroes { get; set; }
    }
}
